# Generated by Django 4.2.2 on 2023-07-20 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kodeKategori', models.CharField(max_length=8)),
                ('nama', models.CharField(max_length=50)),
                ('deskripsi', models.IntegerField()),
            ],
        ),
    ]
